# Generated by Django 4.2.7 on 2024-01-04 03:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_followercount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_post_id', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('community_user', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='community_post')),
                ('likes', models.IntegerField(default=0)),
                ('upload_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('about', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(max_length=200)),
                ('community_id_user', models.IntegerField()),
                ('profile_imag', models.ImageField(default='avatar.png', upload_to='community_profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.communityuser')),
            ],
        ),
    ]
