# Generated by Django 4.2.7 on 2024-01-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_communityprofile_community_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityuser',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
