# Generated by Django 4.2.7 on 2024-01-05 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_savepost_caption_remove_savepost_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypost',
            name='curr_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.profile'),
        ),
    ]
