# Generated by Django 4.2.7 on 2024-01-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_communityfollow_communitylike_communitypost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityuser',
            name='image',
            field=models.ImageField(default='avatar.png', upload_to='community_profile'),
        ),
    ]
