# Generated by Django 4.2.7 on 2024-01-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_communityuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityprofile',
            name='community_id_user',
            field=models.IntegerField(blank=True),
        ),
    ]
