# Generated by Django 4.2.7 on 2024-01-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_communityprofile_community_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityprofile',
            name='community_id_user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
