# Generated by Django 4.2.7 on 2024-01-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_communitypost_curr_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr_user', models.CharField(max_length=100)),
                ('post_user', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='Saved_Post')),
                ('caption', models.CharField(max_length=100)),
                ('likes', models.IntegerField()),
            ],
        ),
    ]
