# Generated by Django 4.2.7 on 2024-01-05 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_savepost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savepost',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='savepost',
            name='image',
        ),
        migrations.RemoveField(
            model_name='savepost',
            name='likes',
        ),
        migrations.AddField(
            model_name='savepost',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.post'),
        ),
    ]
